---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cube

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cube
    spec:
      containers:
        - name: cube
          image: ghcr.io/blomma/cube:main
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
          imagePullPolicy: Always
  selector:
    matchLabels:
      app: cube

---
kind: Service
apiVersion: v1
metadata:
  name: cube

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: cube

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: cube
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - http:
        paths:
          - path: /weatherforecast
            pathType: Prefix
            backend:
              service:
                name: cube
                port:
                  number: 80
